### ISSUE TITLE
Create box-and-line architecture diagram

### ISSUE THREAD

**Issue by TechSolomon** [whbarndt/wrapplotlib#4]
Not to be confused with the [UML](https://en.wikipedia.org/wiki/Unified_Modeling_Language) class diagram.

### Design Tools
- https://mermaid-js.github.io/mermaid/#/
- https://excalidraw.com/
- https://www.diagrams.net/

**Comment by andrewsng** [comment]
The diagram has been added to the draw.io file in the shared drive. Maybe we can discuss adding it to the repo.
